spring:
  application:
    name: bosinsa-batch
  profiles:
    active: local
    include:
      - common
      - domain
    group:
      local: local, domain-local, common-local
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.jdbc: TRACE
  timezone: Asia/Seoul