plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
    id 'java'
}

bootJar { enabled = true }
jar { enabled = false }

dependencies {
    implementation project(':module-domain')
    implementation project(':module-common')
    implementation project(':module-contracts')
    implementation project(':module-external')
    implementation project(':module-messaging')

    // Spring Web, Security
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3', 'io.jsonwebtoken:jjwt-jackson:0.12.3'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // thymeleaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // kafka
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'io.micrometer:micrometer-observation'
}

tasks.named('bootJar') {
    mainClass.set('com.example.api.BosinsaApiApplication')
}

tasks.withType(Test) {
    useJUnitPlatform()
}
