version: '3.8'

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bosinsa
      MYSQL_ROOT_PASSWORD: 1212
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build:
      context: ./module-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  batch:
    build:
      context: ./module-batch
      dockerfile: Dockerfile
