server:
  port: 9090

spring:
  profiles:
    active: local
    include:
      - common
      - domain
    group:
      local: local, domain-local, common-local, external-local
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 1edUaaGpfy135hntJVinhw7gM0nNfM2SPfbDiWEsQtbBYtR8VQxyRP2ooyOm/3tolC/Ok3gW3hr8Haztvs7XLQ==
  expired: 36000000