server:
  port: 9090

spring:
  profiles:
    active: local
    include:
      - common
      - domain
    group:
      local: local, domain-local, common-local, external-local
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    redis:
      host: localhost
      port: 6379